### PR TITLE
dont hide settings menu toggle

### PR DESCRIPTION
**Pull request by icewind1991**

### CODE REVIEW

**Comment by juliusknorr** [comment]
Can you please provide some more detailed information, why this change is needed?

**Comment by icewind1991** [comment]
The css that hides the apps dropdown also hides the settings/logout dropdown

before:



after:

**Comment by Akhenaton** [comment]
Same here with ownCloud 8.2.1
 (hides the settings/logout dropdown permanently)

**Comment by juliusknorr** [comment]
OK, now i get it. Thanks for your contribution. :)

**Comment by Akhenaton** [comment]
Perfect now with version 0.5 ! Thank you for this very nice app.

**Pull request merged**
